### ISSUE TITLE
这个仓库是干啥的

### ISSUE THREAD

**Issue by hellojukay** [LinuxSuRen/ssh-hosts#1]

**Comment by hellojukay** [comment]
能介绍一下吗，我也想参与进来。

**Comment by LinuxSuRen** [comment]
在用 ssh 命令的时候，我们经常会配置 `~/.ssh/config`，方便 ssh 登录。尤其是在内网开发中，会在虚拟机上开发调试，我就想着把 ssh 配置文件中的机器配置同步到 `/etc/hosts` 中。这样的话，在虚拟机上登录后，就可以用域名来登录了。

**Comment by LinuxSuRen** [comment]
基本功能还没完成，我先提交一个版本的代码。

**Comment by hellojukay** [comment]
是说把本地机上的 `$HOME/.ssh/config` 中的 机器的别名 ，同步到服务器上的 /etc/hosts 吗

**Comment by LinuxSuRen** [comment]
> 是说把本地机上的 `$HOME/.ssh/config` 中的 机器的别名 ，同步到服务器上的 /etc/hosts 吗


是的，是这个意思。

**Comment by LinuxSuRen** [comment]
基本功能已经实现。
